apiVersion: v1
kind: Service
metadata:
  name: system-monitor
  labels:
    app: system-monitor
spec:
  type: LoadBalancer
  selector:
    app: system-monitor
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
